<?php

namespace App\Filament\Resources\OrderResource\Pages;

use App\Filament\Resources\OrderResource;
use Filament\Actions;
use Filament\Resources\Pages\EditRecord;

class EditOrder extends EditRecord
{
    protected static string $resource = OrderResource::class;

    protected function getRedirectUrl(): ?string
    {
        return $this->getResource()::getUrl('index'); // TODO: Change the autogenerated stub
    }


    protected function getSavedNotificationTitle(): ?string
    {
        return 'Order updated successfully';
    }

    protected function getHeaderActions(): array
    {
        return [
            Actions\DeleteAction::make(),
        ];
    }
}
